### ISSUE TITLE
Syntax theme shows up in packges rather than Themes

### ISSUE THREAD

**Issue by MarcusE1W** [Niishi/pikachu-syntax#1]
Hi.

Your syntax is listed on Atom.io under Packages rather than Themes.

Happened to me as well and I never got to the bottom of it but unpublishing and publishing it again eventually solved it, since then I had no more problems.
No idea if in any way related, but I also have set the ATOM_ACCESS_TOKEN variable to my token.

Nice work btw 

ps.
I just see that you also created the Pear syntax. That has influenced my Eastend Theme quite a lot :smile:

**Comment by Niishi** [comment]
Thank you, MarcusE1W.

My English is not good, so I don't understand what you mean.
In my screen, "pikachu-syntax" shows up in themes.

![pic1](https://user-images.githubusercontent.com/16276236/40783655-18fd20e8-651e-11e8-9f5f-6a3c19bbbd76.png)
![pic2](https://user-images.githubusercontent.com/16276236/40783660-1dc51a90-651e-11e8-92ae-6491baf64e66.png)

I might have misunderstood your comment.

**Comment by MarcusE1W** [comment]
I see what you mean.

I see it under packages, but I see it only in the section "Newest".
Maybe that section shows Themes and Packages?

I close this :smile:
